language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: Y6reDFX9KTKu+LR7hcf1ejiNOVnh3GEVdOKLwE5jaDSV65KbgrKWxK8NyQpv+B5xe0NDviSIbfve8dkeKQPCyBNKueM804gypefc04Xr1GesdUSul9xoODGhKgRLmJNXjb4RYtaV0QUeVxXDzdD7DIM6b1VMczeulB8b2SUxhsYQzA6JJu8nQ3kU+xQHjhdgdf2m2A+ckH6s3W2yc8IFmwZt1Zb5+QMhJOxtgoKJKVtDRorn2tmucKUq3ityPsrMhqKgGEfBQKMDyxtnZ1J8nXVFai0Eu+qWZcrq13EDPrFM0uLFoFy/GIbIYMrdck8ybJ/6HSgHGUJsgm3qiKGjRjdSvwmqYaIpd49WGVncFlMXF6bDJ2B9uXdOkqlhbTrRKe3lxApQmod3gH40GuVjWVml/PR25+Lua67XoXGrHzYSN54+aAVPtJo3S0uJU/Jwro5l3otQr4uJCV3dCXwr2ujm7NtZsYg9L7cBYLCywHVPnYOPkvyIl8I8ufFLdkAsQuEE20+/2VOKW6xcs2FQOMGM/xlRdZrLGitIgs5Jcr+bcf933Yt0j8fEuPrB/H/HHH721QSv4McWi4hTvEgDaEmZ3WaUPrHlPZ5oGC0JfZ9eJSUbO1HJNgVnm4PJu0E/IKZN10NwlOZfw8voSaKeBFB+1MhVUmxRDA7xXbIjMHQ=
  api_key:
    secure: inVklW3C1bAM8k6v31NtE72ZxdywAIPod8iU4c5h4GPdjvNrscmNBDkyLmAGHKAq9DrQCeF8uW+KUZsu3Eem0js0GqGU2usLMdfZqbVVLKRbXgh0YXNIjR0PMJxq7NMEemsMtAql4qBbPQ77XK9qx6hSPhHB8nWoHkk30sM9AuKOLGbIJnt1Nsr3AKaVfHFokQEbVkGCf9pelhZ5xoFNUPx+5kveom1j/DBmZtn9lZhFRbvTTKtXT29D6mhZXm8bWXaCtSjy9dzosVtpxUraXy0i+x8lhiGkKtjOVEKsS8yXMucEI9tkw5RcvDaL7jrVgyfDle4nXhEov7MKPOt6pwFfugJelQbf9FByogiRDieGCWPs4rBE7BusXYEm1xMvyt3iIk15SkfiKFxmXpvL3dgIa7P15Qwfaf7SLs/UIPfbQyaDKhVvFQOf2lhmwT2XGyitmRm/TZ96JnMWLlRtsdYl4ocgSziPlv7EDYYnnYPQCR++dKHtOzCcVs7T5G956xvcmMvT2LGaFf3fKih24YmOC7d5Lpj72TqmACDf5G38HsVly88emXwfhCg6ao7QOniw8oLg96QZYecRDQwB1thVX7LBLKBgOlJkwhiZRtQUh2rlT26Ih/B0H3+EYrRvAQQTrcDuXqqn6HTxQDmsT8nk+8sMydWWTQhdn0rczzk=
  on:
    tags: true
    repo: thelounge/thelounge-theme-classic
    branch: master
