language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: SS7o8vYspfDU0CKsfz5F5ktZVGKryulOvLTUckOnVrtSgTbMomhp2UGR727mik0HD3TwS5pCHyZCZpre6foBBNT6zGRVA+pLQsnw0nwCg7+uxWf5vz712HillbyZRIVE4FU+HfnaIPoCBmNntRuPWr/dYljUJyYP2I007PSDt6D+du5EkWAUksuN+GaSPAKuZ7VP35YGww0lW6IJ7GFpXc2LYewnCabdU9ZOVxg52ydiFL1BlQ5u/1PT1GIz5NVml9eG1mKDMn+jZPmsHkSHcV4PNoCB5UmmyQKuuJCASPOe5QqzMrmeCFQQ4g4sTJBWIJAPnrYlpFI0pbtAGcsrtoSlW9HWV56uI0HPiwvpODVN7XYoqO1zd7ne62CHtbJR6JgWQdT89RiZdx3IXkJzL3jYFv8XLrVZmq7oufqM+Xtqvieiv8FMUmp5vHGXZDG6ZGttXjqDIn/XR+ZWuFoWktYN3yPBGBW3B517V5QpqdKltjxbqjIqvEyCFpvY2Yod0S62IczcQZ6S7dItvc43mIKY/7t2AlG3BEF6PuvbzWWu9GGPs8yeu0uAxbAHeYXfe/1QrSrsVUtQBCERmzlKY1lTXXFND4IltkSGlpfL+GzfuBTAvY3d/MVnpIJM8dzp2wy8srQqAV35ip3RH4DKj4WMp5zdMXZnIGHNjb0X81U=
  api_key:
    secure: eOLilG0GWxskM6w7FPUbY5aK2l9FV7vzI83GCCtf+CrshnRl0Ncwos77gd887rVa3+6qHytuSydUFlYra3hXvJsPqnmuFqv6LACFONCe0WWxFNzYqmvJOQC226ghd0w16HrAkx91h3Rkro928Gw7mm03A+4llAEF/sD6m9pZfKBrnbSDiZNNJyAgZIQhh2Gy/eYo9xVP0evFaYddGD5CE76lfcAhasdfk35pT4FnyX0k1yQKF1OrBdGLjNUYkqtYUCMMy7GsqVnpauUyEk7IAQtzG/kI5BrKbUR6xVzCREs26MKvlCU5MifaFEQrsTcodREqOIjW1AY9BqUK4x2vFFmYsPlcBZwGUYq0WUXsjURP+QHLYrY5hGLDRe9XdZrhtQOOGpSPZh2+1K94iHRElqMHCBvrRrZAm3QLea49EE3eqq278f0UuQj+47kCKXCE7OlJupNfLz1VOMTzlAIWEYrj0W6sB0YwFZRatq2CYZU+EDd5hqiQ1CAeIYrZrY+cCox0rOmDI1zy4q7TIAA+3WvIet+TGFW/eb3C35qTv3szZJAzEnhk5Gy+b1FBfOpCe/ZsS27kFlO0ytJBv5TpkNkg9Qxy0YYPpjKEMz9HduB5yvQ2LLiH7JbLoiniHc2cTp908uOg5QwXq1rJqXYz7VrqahcyqLVLm44KF537LxY=
  on:
    tags: true
    repo: thelounge/thelounge-theme-classic
    branch: master
