language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: H+u+056rze8JCue+9aeZBLqFdl7TJ7yWngEDPe8IUK5Ul80lslHcrp42ESGCETRH16OO6pgJndZfBSwyZd5uyHMlUOr50CHoIzsljbZ1ZeZs1Q3MqAJsJJCfPDMulysye9meh/it4fhLWLKaClDjzmpXXCeqOOQ9uKHnOebkcgmYYrmmXcvtbN+4IOT/WqqdDXTa3j8xl/QNfdXkXXVG7Yp7SlDOPJa4l1KRLW9N3BYyKFpG2DyrSMR2GmBvk5z25yi2ZqsNmRzMU6BG16leUNP6Vkg5ZHbOMqwZ9O5fJxxrLn9pNd6UcCPjX7BiWwW6/z/VuOXg1MZaijJn1jVHDPjk/oGKpkiIJGh9barXDb1jNjE6pY2E+WjRTUgOvfdsTVZREPYMLEcRGOwxejft4x/bCYB0utzKkTE7BPw+f13OZ3kTxrkbRb8GxYb7PcxTCSXMALpmys6J6F0ZZ3ZNr0loqEnBSgAGR5d/vl0qWe1FzaGoAda2chZHpAyefo5Da6X9obRW+EayJsC/IaZjIK28bgaVzm3vuxzmqvxKIN5nPupGjB9u+QQXE6pSeAE9wRUl23pK0dAytE/63QKCb6gpU/D0PWrUxmj1LfPd3wvZUPD4mTDjaagzCX/JrT+9u/q0iAOCDXmrzg32xeRDO5CbAApJIui6D2uIH7BBj3U=
  api_key:
    secure: bqeB5VpPQ8ShGvSMRmxLULmz/yy2LHdR6gSXoPz9+Jn6OW7mYq/JkyCPib6/GDpyNS71MaJvKsqR4yTrbUgb0jH8a/f8PGgrRFuCigh8TMqGaZHNTaVNVyBBL0bgBE1dz0c+y/zkhwrrWEY6HT6JVcxHX3YHzwfUd/Cwfw1a/qJuU3z9llrs6PEqeigfy+CtHMdU0FiNDWMa9sqfwWFEDDFH/WSVlmjRClfpn/nMePM9aAdwXMMgE2JxWHyLNCsOjMFkvPtM4Azm66MGu8pU16mRo0HpIhQ+eawKSHNQinD4nm3+oBbYLdxTfkx0UqEAIhJUB+wAd3bu6LW6hI7eQdc3+mdiFPgtSeuZjytx5avWxjKAISdg79u41w26IjCBmlzPznIJxZeFKQ8Ai8kakJ4FtKnS23jowLNS0PnVpMU32puqYY6Ye7Tt7xNArZJJziaR+j0hyoxFtdGmid4Chf6MTGr2YVJ6u32pzy9UG95NiguPNWKoqJorLB6xpuSo1Ig33fTEjI6ft3M08i8rRC3pXcTUOwevux5KuzR9z5mv5r345BS0depzlXdb65eeLW6C64+gPV9J1Izk2AaFH1Xazsxz/GZr40kSq+/NpEM0nfAP596JWf2CHWIec9YZuIwYSLpCLzS7eNVICGoZymVg/d2/5aLZ5+ma62910jk=
  on:
    tags: true
    repo: thelounge/thelounge-theme-classic
    branch: master
