language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: Q7+wkOI+TGHZxP8LWArhljNvgKMyAbBSZ5bo/VWY0lmsJWWses5srQEs18p3mYD8tGPCtzlYetAPBbQPOXHMQfzu8nol+zy61qVs/pvjEdLWEZy/Hho/KHs31Z0+i/o4CM0GfD0xDAURKhVZlSpusM/Kc557TjTGE0sk/ipSAzDZxj5SPnAv3JeUnkd5L+cllcnFzjsVZ+29mndTcjgP12RcxaTn0JUGTHSqhnOqXi2NZykb4Cg91vdwnFFiX4OQxFnhPQ0fE2nz/hYWrbDOnBhhTk1wJ4Puol7e2tdI4e78ar+XA5Blam0fiubefeAilwyMAZBiHdS0w+KyjNgKpHKOVQccWENRqvu4k40F5WZT7sWsPUGv64RSQaABb9o2cF5Wzi9XUXbZCOKRrXSvGZLHPeaCdelkCxS8q/xBcGH0C7ZiqY30Ecoz7Uqiha6cdZNK7EmWnhV6kIbE9LGiHaus0w4GUXs2lpvEQxYa83JRX0Tds8N95jaa/4g0GnB+XGnGQ3NxYFyO6plweTyQPERpYdwEoVsJiYfCCQDFzNSqy+TU/jGQkXFnM8vFdWREsHmTm508ydXndH4xIG3iMCK5nw1lV1F0NrX/gPxBFFa2OvN7Wg2+YX85oHlnTiTgCTjqWnUY5n1XFG/dnMZxUs/wzf7RXdbpPgDrY+updu4=
  api_key:
    secure: inVklW3C1bAM8k6v31NtE72ZxdywAIPod8iU4c5h4GPdjvNrscmNBDkyLmAGHKAq9DrQCeF8uW+KUZsu3Eem0js0GqGU2usLMdfZqbVVLKRbXgh0YXNIjR0PMJxq7NMEemsMtAql4qBbPQ77XK9qx6hSPhHB8nWoHkk30sM9AuKOLGbIJnt1Nsr3AKaVfHFokQEbVkGCf9pelhZ5xoFNUPx+5kveom1j/DBmZtn9lZhFRbvTTKtXT29D6mhZXm8bWXaCtSjy9dzosVtpxUraXy0i+x8lhiGkKtjOVEKsS8yXMucEI9tkw5RcvDaL7jrVgyfDle4nXhEov7MKPOt6pwFfugJelQbf9FByogiRDieGCWPs4rBE7BusXYEm1xMvyt3iIk15SkfiKFxmXpvL3dgIa7P15Qwfaf7SLs/UIPfbQyaDKhVvFQOf2lhmwT2XGyitmRm/TZ96JnMWLlRtsdYl4ocgSziPlv7EDYYnnYPQCR++dKHtOzCcVs7T5G956xvcmMvT2LGaFf3fKih24YmOC7d5Lpj72TqmACDf5G38HsVly88emXwfhCg6ao7QOniw8oLg96QZYecRDQwB1thVX7LBLKBgOlJkwhiZRtQUh2rlT26Ih/B0H3+EYrRvAQQTrcDuXqqn6HTxQDmsT8nk+8sMydWWTQhdn0rczzk=
  on:
    tags: true
    repo: thelounge/thelounge-theme-classic
    branch: master
